### ISSUE TITLE
Bug in CurrentUrlPath of BrowserWrapper

### ISSUE THREAD

**Issue by tomasherceg** [riganti/selenium-utils#17]
If I understand correctly, the `browser.CurrentUrlPath` should return the path component of the URL.
However, the following line returns the entire URL.

https://github.com/riganti/selenium-utils/blob/d312796fe2d2c12464e1e17634b07d5b7aee5455/src/Core/Riganti.Selenium.Core/BrowserWrapper.cs#L92

I guess it can be changed to `AbsolutePath` to fix the behavior.

Can you please confirm that I understand correctly what the property shall do so that I can create a PR?

**Comment by quigamdev** [comment]
Yes, only the path of the URL should be returned (without host).

**Comment by quigamdev** [comment]
I have opened PR for this issue. Please review it and feel free to merge it.
